# Generated by Django 3.2.8 on 2022-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='images',
            field=models.ImageField(default='images/others/igor-lypnytskyi-PobecUzsK4c-unsplash.png', help_text='Upload song image', upload_to='images/uploads/', verbose_name='image'),
        ),
    ]
