# Generated by Django 3.2.8 on 2022-10-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20221003_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
